<? include "header.tpl" ?>
<article>
	<div class="col-md-offset-1 col-md-10">
		<h1><?=$this->title?></h1>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus quam neque, sed, dolorem pariatur repellat. Dolorem libero enim debitis, quo harum cum exercitationem animi, atque aperiam pariatur neque, accusamus ex?</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus quam neque, sed, dolorem pariatur repellat. Dolorem libero enim debitis, quo harum cum exercitationem animi, atque aperiam pariatur neque, accusamus ex?</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus quam neque, sed, dolorem pariatur repellat. Dolorem libero enim debitis, quo harum cum exercitationem animi, atque aperiam pariatur neque, accusamus ex?</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus quam neque, sed, dolorem pariatur repellat. Dolorem libero enim debitis, quo harum cum exercitationem animi, atque aperiam pariatur neque, accusamus ex?</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus quam neque, sed, dolorem pariatur repellat. Dolorem libero enim debitis, quo harum cum exercitationem animi, atque aperiam pariatur neque, accusamus ex?</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus quam neque, sed, dolorem pariatur repellat. Dolorem libero enim debitis, quo harum cum exercitationem animi, atque aperiam pariatur neque, accusamus ex?</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus quam neque, sed, dolorem pariatur repellat. Dolorem libero enim debitis, quo harum cum exercitationem animi, atque aperiam pariatur neque, accusamus ex?</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus quam neque, sed, dolorem pariatur repellat. Dolorem libero enim debitis, quo harum cum exercitationem animi, atque aperiam pariatur neque, accusamus ex?</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus quam neque, sed, dolorem pariatur repellat. Dolorem libero enim debitis, quo harum cum exercitationem animi, atque aperiam pariatur neque, accusamus ex?</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus quam neque, sed, dolorem pariatur repellat. Dolorem libero enim debitis, quo harum cum exercitationem animi, atque aperiam pariatur neque, accusamus ex?</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus quam neque, sed, dolorem pariatur repellat. Dolorem libero enim debitis, quo harum cum exercitationem animi, atque aperiam pariatur neque, accusamus ex?</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus quam neque, sed, dolorem pariatur repellat. Dolorem libero enim debitis, quo harum cum exercitationem animi, atque aperiam pariatur neque, accusamus ex?</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus quam neque, sed, dolorem pariatur repellat. Dolorem libero enim debitis, quo harum cum exercitationem animi, atque aperiam pariatur neque, accusamus ex?</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus quam neque, sed, dolorem pariatur repellat. Dolorem libero enim debitis, quo harum cum exercitationem animi, atque aperiam pariatur neque, accusamus ex?</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus quam neque, sed, dolorem pariatur repellat. Dolorem libero enim debitis, quo harum cum exercitationem animi, atque aperiam pariatur neque, accusamus ex?</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus quam neque, sed, dolorem pariatur repellat. Dolorem libero enim debitis, quo harum cum exercitationem animi, atque aperiam pariatur neque, accusamus ex?</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus quam neque, sed, dolorem pariatur repellat. Dolorem libero enim debitis, quo harum cum exercitationem animi, atque aperiam pariatur neque, accusamus ex?</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus quam neque, sed, dolorem pariatur repellat. Dolorem libero enim debitis, quo harum cum exercitationem animi, atque aperiam pariatur neque, accusamus ex?</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus quam neque, sed, dolorem pariatur repellat. Dolorem libero enim debitis, quo harum cum exercitationem animi, atque aperiam pariatur neque, accusamus ex?</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus quam neque, sed, dolorem pariatur repellat. Dolorem libero enim debitis, quo harum cum exercitationem animi, atque aperiam pariatur neque, accusamus ex?</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus quam neque, sed, dolorem pariatur repellat. Dolorem libero enim debitis, quo harum cum exercitationem animi, atque aperiam pariatur neque, accusamus ex?</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus quam neque, sed, dolorem pariatur repellat. Dolorem libero enim debitis, quo harum cum exercitationem animi, atque aperiam pariatur neque, accusamus ex?</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus quam neque, sed, dolorem pariatur repellat. Dolorem libero enim debitis, quo harum cum exercitationem animi, atque aperiam pariatur neque, accusamus ex?</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus quam neque, sed, dolorem pariatur repellat. Dolorem libero enim debitis, quo harum cum exercitationem animi, atque aperiam pariatur neque, accusamus ex?</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus quam neque, sed, dolorem pariatur repellat. Dolorem libero enim debitis, quo harum cum exercitationem animi, atque aperiam pariatur neque, accusamus ex?</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus quam neque, sed, dolorem pariatur repellat. Dolorem libero enim debitis, quo harum cum exercitationem animi, atque aperiam pariatur neque, accusamus ex?</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus quam neque, sed, dolorem pariatur repellat. Dolorem libero enim debitis, quo harum cum exercitationem animi, atque aperiam pariatur neque, accusamus ex?</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus quam neque, sed, dolorem pariatur repellat. Dolorem libero enim debitis, quo harum cum exercitationem animi, atque aperiam pariatur neque, accusamus ex?</p><p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus quam neque, sed, dolorem pariatur repellat. Dolorem libero enim debitis, quo harum cum exercitationem animi, atque aperiam pariatur neque, accusamus ex?</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus quam neque, sed, dolorem pariatur repellat. Dolorem libero enim debitis, quo harum cum exercitationem animi, atque aperiam pariatur neque, accusamus ex?</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus quam neque, sed, dolorem pariatur repellat. Dolorem libero enim debitis, quo harum cum exercitationem animi, atque aperiam pariatur neque, accusamus ex?</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus quam neque, sed, dolorem pariatur repellat. Dolorem libero enim debitis, quo harum cum exercitationem animi, atque aperiam pariatur neque, accusamus ex?</p>
	</div>
	<div class="clear"></div>
</article>
<? include "footer.tpl"?>